unit Opcodes;

interface

const
  S_LOGIN = $1;
  S_CHARLIST = $5;
  S_SELECT_CHARACTER = $13;
  S_PLAYER_LOGGEDIN = $14;
  S_PONG = $1A;
  S_SELECT_CHARACTER_PIC = $1E;
  S_CLIENT_START = $23;
  S_CHANGE_MAP = $2A;
  S_CHANGE_CHANNEL = $2B;
  S_MOVE = $2D;
  S_CHAT = $36;
  S_FACE = $39;
  S_NPC_TALK = $40;
  S_NPC_TALK_MORE = $42;
  S_USE_ITEM = $50;
  S_SKILL = $6A;
  S_CANCEL_BUFF = $6B;
  S_CHANGE_MAP_SPECIAL = $73;
  S_MOB_DAMAGE_MOB = $EF;
  S_TAKE_DROP = $FD;

  R_LOGINSTATUS = 0;
  R_CONNECT_AUTH = $2;
  R_CHARACTER_LIST = $B;
  R_SERVER_IP = $C;
  R_CHANGE_CHANNEL = $10;
  R_PING = $11;
  R_MODIFY_INVENTORY = $1C;
  R_UPDATE_STATS = $1E;
  R_GIVE_BUFF = $21;
  R_CANCEL_BUFF = $3A6;
  R_REMOVE_TEMPORARY_STATS = $22;
  R_UPDATE_SKILLS = $25;
  R_SHOW_INFO = $26;
  R_NOTES = $28;
  R_ENABLE_REPORT = $2E;
  R_UPDATE_MOUNT = $2F;
  R_GENDER = $3A;
  R_PARTY_OPERATION = $3E;
  R_BUDDY_LIST = $41;
  R_GUILD_OPERATION = $43;
  R_SERVER_MESSAGE = $47;
  R_EVENT_STAT = $5D;
  R_OPEN_FAMILY = $63;
  R_WARP_TO_MAP = $8F;
  R_SPAWN_PLAYER = $B6;
  R_REMOVE_PLAYER = $B7;
  R_CHAT = $B8;
  R_SHOW_ITEM_GAIN_INCHAT = $EE;
  R_SPAWN_MONSTER = $127;
  R_REMOVE_MONSTER = $128;
  R_MONSTER_HP = $135;
  R_SPAWN_NPC = $143;
  R_SPAWN_DROP = $14E;
  R_NPC_TALK = $17F;

implementation

end.
